quick-check:
    iterations: 5
    seed: 1
    max-size: 50
compare:
#    method: SQDIFF
    method: SQDIFF_NORMED
    threshold: 0.00003
#    threshold: 10.0
web:
    host: 192.168.2.3
    port: 3000
    dir: "gen"
browsers:
    - type: firefox
      host: 192.168.2.3
      port: 7000
    - type: chrome
      host: 192.168.2.3
      port: 7001
    - type: servo
      host: 192.168.2.3
      port: 7002
