(* Base CSS Types: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types *)

nonprop-angle = nonprop-number ( 'deg' | 'grad' | 'rad' | 'turn' ) ;
(* nonprop-basic-shape = ; *)
(* nonprop-blend-mode = ; *)
(* nonprop-color = ; *)
(* https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident *)
nonprop-custom-ident = #'(?:[A-Za-z_]|-[A-Za-z_]|\\[0-9A-F]{1,6})(?:[A-Za-z0-9_-]|\\[0-9A-F]{1,6})+' ;
nonprop-flex = nonprop-number 'fr' ;
nonprop-frequency = nonprop-number ( 'Hz' | 'kHz' ) ;
(* nonprop-gradient = ; *)
(* nonprop-image = ; *)
nonprop-integer = #'-?[0-9]+' ;
nonprop-length = nonprop-number length-unit
               | '0' ;
nonprop-number = nonprop-integer | number-float ;
nonprop-percentage = nonprop-number '%' ;
(* nonprop-position = ; *)
nonprop-ratio = nonprop-positive-integer '/' nonprop-positive-integer ;
nonprop-resolution = nonprop-number ( 'dpi' | 'dpcm' | 'dppx' | 'px' ) ;
(* nonprop-shape = ; *)
(* TODO: improve strings: https://developer.mozilla.org/en-US/docs/Web/CSS/string *)
nonprop-string = #"'[A-Za-z0-9 _\"\-^]*'"
               | #"\"[A-Za-z0-9 _'\-^]*\"" ;
nonprop-time = nonprop-number ( 's' | 'ms' ) ;
(* nonprop-transform-function = ; *)
(* TODO: improve urls: https://developer.mozilla.org/en-US/docs/Web/CSS/url *)
nonprop-url = 'url(' url ')'
            | 'url("' url '")' ;

nonprop-positive-integer = #'[0-9]+' ;

nonprop-unicode-range = #'U[+](?:[0-9A-Fa-f]{1,4}-[0-9A-Fa-f]{1,4}|[0-9A-Fa-f?]{1,4})' ( ',' S nonprop-unicode-range )* ;

nonprop-ident-token = "STUB_ident_token" ;
nonprop-declaration = "STUB_declaration" ;
nonprop-calc-sum = "STUB_calc_sum" ;

nonprop-charset = charset ;

(* non-standard needed by at-rules *)

nonprop-font-variation-settings = prop-unknown ;


(* standard nonprop -> prop mappings *)
(* TODO: fix so we don't have to do this *)

nonprop-align-content = prop-align-content ;
nonprop-align-items = prop-align-items ;
nonprop-justify-content = prop-justify-content ;
nonprop-justify-items = prop-justify-items ;
nonprop-align-self = prop-align-self ;
nonprop-justify-self = prop-justify-self ;
nonprop-padding-left = prop-padding-left ;
nonprop-row-gap = prop-row-gap ;
nonprop-column-gap = prop-column-gap ;

nonprop-top = prop-top ;
nonprop-bottom = prop-bottom ;
nonprop-left = prop-left ;
nonprop-right = prop-right ;

nonprop-background-color = prop-background-color ;

nonprop-border-top-color = prop-border-top-color ;
nonprop-border-top-width = prop-border-top-width ;
nonprop-border-top-style = prop-border-top-style ;
nonprop-border-width = prop-border-width ;
nonprop-border-style = prop-border-style ;
nonprop-border-radius = prop-border-radius ;
nonprop-border-image-source = prop-border-image-source ;
nonprop-border-image-slice = prop-border-image-slice ;
nonprop-border-image-width = prop-border-image-width ;
nonprop-border-image-outset = prop-border-image-outset ;
nonprop-border-image-repeat = prop-border-image-repeat ;

nonprop-column-width = prop-column-width ;
nonprop-column-count = prop-column-count ;
nonprop-column-rule-width = prop-column-rule-width ;
nonprop-column-rule-style = prop-column-rule-style ;
nonprop-column-rule-color = prop-column-rule-color ;

nonprop-flex-direction = prop-flex-direction ;
nonprop-flex-wrap = prop-flex-wrap ;
nonprop-flex-grow = prop-flex-grow ;
nonprop-flex-shrink = prop-flex-shrink ;
nonprop-flex-basis = prop-flex-basis ;

nonprop-font-feature-settings = prop-font-feature-settings ;
nonprop-font-style = prop-font-style ;
nonprop-font-weight = prop-font-weight ;
nonprop-font-stretch = prop-font-stretch ;
nonprop-font-size = prop-font-size ;
nonprop-font-family = prop-font-family ;
nonprop-font-variant = prop-font-variant ;

nonprop-grid-template = prop-grid-template ;
nonprop-grid-template-rows = prop-grid-template-rows ;
nonprop-grid-template-columns = prop-grid-template-columns ;
nonprop-grid-auto-rows = prop-grid-auto-rows ;
nonprop-grid-auto-columns = prop-grid-auto-columns ;

nonprop-line-height = prop-line-height ;

nonprop-list-style-type = prop-list-style-type ;
nonprop-list-style-position = prop-list-style-position ;
nonprop-list-style-image = prop-list-style-image ;

nonprop-margin-left = prop-margin-left ;

nonprop-mask-image = prop-mask-image ;
nonprop-mask-repeat = prop-mask-repeat ;
nonprop-mask-origin = prop-mask-origin ;
nonprop-mask-clip = prop-mask-clip ;

nonprop-outline-color = prop-outline-color ;
nonprop-outline-style = prop-outline-style ;
nonprop-outline-width = prop-outline-width ;

nonprop-text-emphasis-style = prop-text-emphasis-style ;
nonprop-text-emphasis-color = prop-text-emphasis-color ;
nonprop-text-decoration-line = prop-text-decoration-line ;
nonprop-text-decoration-style = prop-text-decoration-style ;
nonprop-text-decoration-color = prop-text-decoration-color ;

nonprop-width = prop-width ;
nonprop-max-width = prop-max-width ;
nonprop-min-width = prop-min-width ;


(* non-standard nonprop -> prop mappings *)

(*
nonprop--ms-content-zoom-limit-max = prop--ms-content-zoom-limit-max
nonprop--ms-content-zoom-limit-min = prop--ms-content-zoom-limit-min
nonprop--ms-content-zoom-snap-points = prop--ms-content-zoom-snap-points
nonprop--ms-content-zoom-snap-type = prop--ms-content-zoom-snap-type
nonprop--ms-scroll-limit-x-max = prop--ms-scroll-limit-x-max
nonprop--ms-scroll-limit-y-max = prop--ms-scroll-limit-y-max
nonprop--ms-scroll-limit-x-min = prop--ms-scroll-limit-x-min
nonprop--ms-scroll-limit-y-min = prop--ms-scroll-limit-y-min
nonprop--ms-scroll-snap-points-x = prop--ms-scroll-snap-points-x
nonprop--ms-scroll-snap-points-y = prop--ms-scroll-snap-points-y
nonprop--ms-scroll-snap-type = prop--ms-scroll-snap-type
nonprop-font-variation-settings = prop-font-variation-settings
nonprop-grid-row-gap = prop-grid-row-gap
nonprop-grid-column-gap = prop-grid-column-gap
nonprop-mask-border-mode = prop-mask-border-mode
nonprop-mask-border-outset = prop-mask-border-outset
nonprop-mask-border-slice = prop-mask-border-slice
nonprop-mask-border-repeat = prop-mask-border-repeat
nonprop-mask-border-source = prop-mask-border-source
nonprop-mask-border-width = prop-mask-border-width
nonprop-offset-anchor = prop-offset-anchor
nonprop-offset-distance = prop-offset-distance
nonprop-offset-position = prop-offset-position
nonprop-offset-path = prop-offset-path
nonprop-offset-rotate = prop-offset-rotate
*)

(* Other Misc Missing *)
(* TODO: figure out why these are missing. *)

nonprop-hex-color = #'#[0-9A-Fa-f]{3}'
                  | #'#[0-9A-Fa-f]{6}' ;

nonprop-id-selector = nonprop-custom-ident ;
nonprop-ident = nonprop-custom-ident ;
nonprop-dimension = nonprop-resolution ;

func-path = "STUB_func_path" ;
nonprop-an-plus-b = "STUB_an_plus_b" ;
nonprop-any-value = "STUB_any_value" ;
nonprop-attr-name = "STUB_attr_name" ;
nonprop-attr-fallback = "STUB_attr_fallback" ;
nonprop-clip-style = "STUB_clip_style" ;
nonprop-custom-property-name = "STUB_custom_property" ;
nonprop-declaration-value = "STUB_declaration_value" ;
nonprop-function-token = "STUB_flex_function_token" ;
nonprop-mask-attachment = "STUB_mask_attachment" ;
nonprop-name-repeat = "STUB_name_repeat" ;
nonprop-string-token = "STUB_string_token" ;
nonprop-x = "11" ;
nonprop-y = "11" ;


(* TODO: from at-rule descriptors *)

nonprop-counter-system = "STUB_counter_system" ;
nonprop-counter-symbols = "STUB_counter_symbols" ;
nonprop-additive-symbols = "STUB_additive_symbols" ;
nonprop-negative-symbol = "STUB_negative_symbol" ;
nonprop-prefix = "STUB_prefix" ;
nonprop-suffix = "STUB_suffix" ;
nonprop-range = "STUB_range" ;
nonprop-padding = "STUB_padding" ;
nonprop-speak-as = "STUB_speak_as" ;
nonprop-page-body = "STUB_page_body" ;

nonprop-group-rule-body = "STUB_nonprop_group_rule_body" ;
prop-group-rule-body = "STUB_prop_group_rule_body" ;
nonprop-declaration-list = "STUB_declaration_list" ;
