(*
Definitions used for created generators and parsing HTML generated
by those generators.
*)

html-test = '<html>' head-test body-test '</html>'

head-test = '<head>' normalize-css rend-css title-test? '</head>'

normalize-css = '<link rel="stylesheet" href="/static/normalize.css">'

rend-css = '<link rel="stylesheet" href="/static/rend.css">'

title-test = '<title' (<rS> title-attribute)* '>' content* '</title>'

body-test = '<body' (<rS> body-attribute)* '>' 'x' (element | content)* '</body>'

(* Just include the Ahem glyphs that render differently *)
char-data-test = ' ' | 'p' | '&#x00c9;' | 'X'

comment-test = #'<!--(?:[A-Za-z0-9_<>/\\ .]|-[A-Za-z0-9_<>/\\ .])*-->'

url-test = #'(?:https:|http:)?//[A-Za-z0-9._\-/&#=,?]+'
         | #'[A-Za-z0-9._\-/#=]+'
         | 'data:' mime-type ';base64,' #'[A-Za-z0-9+=/]*'



